### ISSUE TITLE
Crash when issuing sync_tms on operator console

### ISSUE THREAD

**Issue by dasta400** [kej715/DtCyber#139]
**Describe the bug**
I was trying to read a tape after I activated TMS with _activate_tms_. As I wasn't successful (I was getting error RESEX ABORT - TAPE MANAGER when doing _LABEL,TAPE,VSN=CENSUS,UN=LIBRARY_), I tried _sync_tms_ and it crashed DtCyber

**To Reproduce**
1. Go to _[DtCyber Console] Operator >_
2. Enable TMS with _actiavte_tms_
3. sync tape catalog with _sync_tms_
4. It crashes. See error log below

**Expected behavior**
Not a crash.

**Error log**
```
10:27:38 [DtCyber Console] Operator> sync_tms
/opt/DtCyber/NOS2.8.7/sync-tms.js:11
for (const line of iniProps["Equipment.nos287"]) {

ReferenceError: iniProps is not defined
    at Object.<anonymous> (/opt/DtCyber/NOS2.8.7/sync-tms.js:11:28)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49

Node.js v18.19.0
/opt/DtCyber/automation/DtCyber.js:858
            reject(new Error(`${command} exited with status ${code}`));

Error: node exited with status 1
    at ChildProcess.<anonymous> (/opt/DtCyber/automation/DtCyber.js:858:20)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12

Node.js v18.19.0
```

**Desktop (please complete the following information):**
 - OS: Linux Debian 6.1.76-1

**Comment by kej715** [comment]
Corrective code has been pushed to the repository. Use "git pull" to obtain
it.

To clarify ... the bug did not crash DtCyber itself. It crashed the Node.js
script, sync-tms.js, and because this was called from the DtCyber operator
console, it also caused the operator console interface to exit. DtCyber
itself was still running, and it would have been possible to reconnect the
operator interface using, e.g., "telnet localhost 6662". In addition,
scripts such as the shutdown.js script could still have been called from
the command line to shutdown DtCyber gracefully.

**Comment by dasta400** [comment]
Thanks a lot Kevin for the quick response and corrective action.

I can confirm that the issue it's solved. And now I can mount the tapes.

Also, _telnet localhost 6662_ has brought back the console. Something new I learnt for the future.
